# Use the official Node.js image as the base image
FROM node:22.11.0

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build:api

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "dist/apps/api/main"]